/* See UNLICENSE.txt file for license details. */

USE [utilities];
GO

SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.util_Get_SqlVariant_As_NVarCharMax') IS NOT NULL
  DROP FUNCTION dbo.util_Get_SqlVariant_As_NVarCharMax;
GO

SET NUMERIC_ROUNDABORT OFF;
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON;
GO

CREATE FUNCTION dbo.util_Get_SqlVariant_As_NVarCharMax
  (
    @sql_variant SQL_VARIANT
  )
RETURNS NVARCHAR(MAX)
AS
BEGIN
  DECLARE @basetype NVARCHAR(MAX) = UPPER(CONVERT(NVARCHAR(MAX), SQL_VARIANT_PROPERTY(@sql_variant, 'BaseType')));

  DECLARE @result NVARCHAR(MAX) =
    CASE @basetype
      WHEN 'BIGINT' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'BINARY' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'CHAR' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'DATE' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'DATETIME' THEN CONVERT(NVARCHAR(MAX), @sql_variant, 121)
      WHEN 'DATETIME2' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'DATETIMEOFFSET' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'DECIMAL' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'FLOAT' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'INT' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'MONEY' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'NCHAR' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'NUMERIC' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'NVARCHAR' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'REAL' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'SMALLDATETIME' THEN CONVERT(NVARCHAR(MAX), @sql_variant, 121)
      WHEN 'SMALLINT' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'SMALLMONEY' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'TIME' THEN CONVERT(NVARCHAR(MAX), @sql_variant, 14)
      WHEN 'TINYINT' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'UNIQUEIDENTIFIER' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'VARBINARY' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      WHEN 'VARCHAR' THEN CONVERT(NVARCHAR(MAX), @sql_variant)
      ELSE ''
    END;

  RETURN @result;
END;

GO
